# Generated by Django 5.2.7 on 2025-11-25 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appPUC_Planner", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="related_course",
        ),
        migrations.RemoveField(
            model_name="task",
            name="user",
        ),
        migrations.DeleteModel(
            name="SemesterPlan",
        ),
        migrations.DeleteModel(
            name="Task",
        ),
    ]
