# Generated by Django 5.2.8 on 2025-11-27 02:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPUC_Planner', '0002_remove_task_related_course_remove_task_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='degree',
            field=models.CharField(blank=True, help_text='Ex.: Engenharia de Computação, Engenharia de Produção...', max_length=100, verbose_name='curso / habilitação'),
        ),
        migrations.AddField(
            model_name='course',
            name='flow_col_percent',
            field=models.IntegerField(blank=True, help_text='Posição horizontal em porcentagem (2, 34, 50, 75, ...)', null=True, verbose_name='coluna do fluxograma (%)'),
        ),
        migrations.AddField(
            model_name='course',
            name='flow_row',
            field=models.IntegerField(blank=True, help_text='Coordenada vertical (px) do bloco no fluxograma', null=True, verbose_name='linha do fluxograma'),
        ),
        migrations.AddField(
            model_name='course',
            name='syllabus_url',
            field=models.URLField(blank=True, max_length=300, verbose_name='URL da ementa'),
        ),
        migrations.CreateModel(
            name='CourseRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('PRE', 'Pré-requisito'), ('CO', 'Co-requisito')], default='PRE', max_length=3, verbose_name='tipo')),
                ('source', models.ForeignKey(help_text='Disciplina que é o pré/co-requisito.', on_delete=django.db.models.deletion.CASCADE, related_name='relations_from', to='appPUC_Planner.course')),
                ('target', models.ForeignKey(help_text='Disciplina que depende da outra.', on_delete=django.db.models.deletion.CASCADE, related_name='relations_to', to='appPUC_Planner.course')),
            ],
            options={
                'verbose_name': 'Relação de disciplina',
                'verbose_name_plural': 'Relações de disciplinas',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Minha grade', max_length=100, verbose_name='nome da grade')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='ano')),
                ('semester', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1º'), (2, '2º')], null=True, verbose_name='semestre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grade horária',
                'verbose_name_plural': 'Grades horárias',
                'ordering': ['-year', '-semester', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField(choices=[(1, 'Segunda'), (2, 'Terça'), (3, 'Quarta'), (4, 'Quinta'), (5, 'Sexta')], verbose_name='dia da semana')),
                ('start_hour', models.PositiveSmallIntegerField(verbose_name='hora de início')),
                ('duration_hours', models.PositiveSmallIntegerField(default=2, verbose_name='duração (horas)')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_items', to='appPUC_Planner.course')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='appPUC_Planner.schedule')),
            ],
            options={
                'verbose_name': 'Bloco na grade',
                'verbose_name_plural': 'Blocos na grade',
                'unique_together': {('schedule', 'day', 'start_hour', 'course')},
            },
        ),
    ]
