# Generated by Django 5.2.8 on 2025-11-28 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPUC_Planner', '0003_course_degree_course_flow_col_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex.: 1º período, 2º período...', max_length=50, verbose_name='nome do período')),
                ('order', models.PositiveSmallIntegerField(help_text='Ordem do período (1, 2, 3...).', verbose_name='ordem')),
                ('flow_row', models.IntegerField(blank=True, help_text='Coordenada vertical (px) onde o rótulo aparecerá', null=True, verbose_name='linha do fluxograma')),
                ('flow_col_percent', models.IntegerField(default=0, help_text='Posição horizontal em porcentagem (0 = bem à esquerda)', verbose_name='coluna do fluxograma (%)')),
            ],
            options={
                'verbose_name': 'Período',
                'verbose_name_plural': 'Períodos',
                'ordering': ['order'],
            },
        ),
    ]
