# Generated by Django 5.2.8 on 2025-11-27 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPUC_Planner', '0003_course_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pos_left_pct',
            field=models.FloatField(blank=True, help_text='Posição left em porcentagem (0-100) usada pelo layout do fluxograma', null=True, verbose_name='pos_left_pct'),
        ),
        migrations.AddField(
            model_name='course',
            name='pos_top_px',
            field=models.PositiveIntegerField(blank=True, help_text='Posição top em pixels usada pelo layout do fluxograma', null=True, verbose_name='pos_top_px'),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.CharField(blank=True, help_text="Códigos separados por vírgula, ex: 'MAT 4162, ENG 4010'", max_length=500, verbose_name='pré-requisitos'),
        ),
    ]
