# Generated by Django 5.2.9 on 2025-12-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appPUC_Planner", "0004_course_pos_left_pct_course_pos_top_px_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="corequisites",
            field=models.CharField(
                blank=True,
                help_text="Códigos separados por vírgula para co-requisitos, ex: 'CTC 4001, CTC 4002'",
                max_length=500,
                verbose_name="co-requisitos",
            ),
        ),
    ]
