# Generated by Django 5.2.9 on 2025-12-03 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPUC_Planner', '0004_course_pos_left_pct_course_pos_top_px_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='nome')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['nome'],
            },
        ),
        migrations.RemoveField(
            model_name='course',
            name='program',
        ),
        migrations.AddField(
            model_name='course',
            name='cursos',
            field=models.ManyToManyField(blank=True, help_text='Selecione todos os cursos que incluem esta disciplina.', related_name='disciplinas', to='appPUC_Planner.curso'),
        ),
    ]
