# Generated by Django 5.2.9 on 2025-12-04 16:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPUC_Planner', '0005_course_corequisites'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='nome')),
                ('periodos', models.PositiveSmallIntegerField(default=8, help_text='Quantidade total de períodos/semestres do curso.', verbose_name='número de períodos')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['nome'],
            },
        ),
        migrations.RemoveField(
            model_name='course',
            name='pos_left_pct',
        ),
        migrations.RemoveField(
            model_name='course',
            name='pos_top_px',
        ),
        migrations.RemoveField(
            model_name='course',
            name='program',
        ),
        migrations.AddField(
            model_name='course',
            name='syllabus_url',
            field=models.URLField(blank=True, help_text='URL para a ementa oficial da disciplina.', verbose_name='link da ementa'),
        ),
        migrations.CreateModel(
            name='CursoDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.PositiveSmallIntegerField(blank=True, help_text='Período em que a disciplina é ofertada neste curso.', null=True, verbose_name='período')),
                ('posicao', models.PositiveSmallIntegerField(blank=True, help_text='Coluna em que a disciplina deve aparecer no período (1 = primeira coluna).', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)], verbose_name='posição na linha')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacoes', to='appPUC_Planner.curso')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacoes', to='appPUC_Planner.course')),
            ],
            options={
                'verbose_name': 'Disciplina de Curso',
                'verbose_name_plural': 'Disciplinas por Curso',
                'ordering': ['curso__nome', 'periodo', 'posicao', 'disciplina__code'],
                'unique_together': {('curso', 'disciplina')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='cursos',
            field=models.ManyToManyField(blank=True, help_text='Selecione todos os cursos que incluem esta disciplina.', related_name='disciplinas', through='appPUC_Planner.CursoDisciplina', to='appPUC_Planner.curso'),
        ),
    ]
