# Generated by Django 5.2.9 on 2025-12-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPUC_Planner', '0005_curso_remove_course_program_course_cursos'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='period',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Período sugerido (1 = primeiro período).', null=True, verbose_name='período'),
        ),
        migrations.AddField(
            model_name='curso',
            name='periodos',
            field=models.PositiveSmallIntegerField(default=8, help_text='Quantidade total de períodos/semestres do curso.', verbose_name='número de períodos'),
        ),
    ]
