# Generated by Django 5.2.9 on 2025-12-03 21:54

import django.db.models.deletion
from django.db import migrations, models


def copy_existing_course_links(apps, schema_editor):
    table_name = 'appPUC_Planner_course_cursos'
    introspection = schema_editor.connection.introspection
    if table_name not in introspection.table_names():
        return

    CursoDisciplina = apps.get_model('appPUC_Planner', 'CursoDisciplina')

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f'SELECT course_id, curso_id FROM {table_name}')
        rows = cursor.fetchall()

    for course_id, curso_id in rows:
        CursoDisciplina.objects.get_or_create(
            disciplina_id=course_id,
            curso_id=curso_id,
            defaults={'periodo': None},
        )


def restore_course_links(apps, schema_editor):
    table_name = 'appPUC_Planner_course_cursos'
    introspection = schema_editor.connection.introspection
    if table_name not in introspection.table_names():
        return

    CursoDisciplina = apps.get_model('appPUC_Planner', 'CursoDisciplina')

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f'DELETE FROM {table_name}')
        cursor.executemany(
            f'INSERT INTO {table_name} (course_id, curso_id) VALUES (%s, %s)',
            list(CursoDisciplina.objects.values_list('disciplina_id', 'curso_id')),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('appPUC_Planner', '0006_course_period_curso_periodos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='period',
        ),
        migrations.CreateModel(
            name='CursoDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.PositiveSmallIntegerField(blank=True, help_text='Período em que a disciplina é ofertada neste curso.', null=True, verbose_name='período')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacoes', to='appPUC_Planner.curso')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacoes', to='appPUC_Planner.course')),
            ],
            options={
                'verbose_name': 'Disciplina de Curso',
                'verbose_name_plural': 'Disciplinas por Curso',
                'ordering': ['curso__nome', 'periodo', 'disciplina__code'],
                'unique_together': {('curso', 'disciplina')},
            },
        ),
        migrations.RunPython(copy_existing_course_links, restore_course_links),
        migrations.RemoveField(
            model_name='course',
            name='cursos',
        ),
        migrations.AddField(
            model_name='course',
            name='cursos',
            field=models.ManyToManyField(blank=True, help_text='Selecione todos os cursos que incluem esta disciplina.', related_name='disciplinas', through='appPUC_Planner.CursoDisciplina', to='appPUC_Planner.curso'),
        ),
    ]
