# Generated by Django 5.2.9 on 2025-12-05 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPUC_Planner', '0006_curso_remove_course_pos_left_pct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PRE', 'Pré-requisito'), ('CO', 'Co-requisito')], default='PRE', help_text='Tipo do requisito (pré ou co).', max_length=3)),
                ('disciplina', models.ForeignKey(help_text='A disciplina que possui este requisito.', on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='appPUC_Planner.course')),
                ('requisito', models.ForeignKey(help_text='A disciplina que é o pré/co-requisito.', on_delete=django.db.models.deletion.CASCADE, related_name='requisito_para', to='appPUC_Planner.course')),
            ],
            options={
                'verbose_name': 'Requisito de Disciplina',
                'verbose_name_plural': 'Requisitos de Disciplinas',
                'ordering': ['disciplina__code'],
                'unique_together': {('disciplina', 'requisito', 'tipo')},
            },
        ),
    ]
