# Generated by Django 5.2.9 on 2025-12-05 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPUC_Planner', '0007_requisito'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Requisito',
        ),
    ]
