# Generated by Django 5.2.9 on 2025-12-03 22:45

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appPUC_Planner", "0007_remove_course_period_cursodisciplina_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="pos_left_pct",
        ),
        migrations.RemoveField(
            model_name="course",
            name="pos_top_px",
        ),
        migrations.AddField(
            model_name="cursodisciplina",
            name="posicao",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Coluna em que a disciplina deve aparecer no período (1 = primeira coluna).",
                null=True,
                validators=[MinValueValidator(1), MaxValueValidator(8)],
                verbose_name="posição na linha",
            ),
        ),
        migrations.AlterModelOptions(
            name="cursodisciplina",
            options={
                "ordering": ["curso__nome", "periodo", "posicao", "disciplina__code"],
                "verbose_name": "Disciplina de Curso",
                "verbose_name_plural": "Disciplinas por Curso",
            },
        ),
    ]
