# Generated by Django 5.2.9 on 2025-12-04 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPUC_Planner', '0008_remove_course_pos_fields_add_rel_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='syllabus_url',
            field=models.URLField(blank=True, help_text='URL para a ementa oficial da disciplina.', verbose_name='link da ementa'),
        ),
    ]
