# Generated by Django 5.2.8 on 2025-11-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPUC_Planner', '0002_remove_task_related_course_remove_task_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='curso'),
        ),
    ]
